spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, value FROM properties WHERE application=? AND profile=? AND label=?
          order: 1
  datasource:
    url: jdbc:mysql://localhost:3306/configserver
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  profiles:
    active:
    - jdbc

server:
  port: 8888
security:
  user: root
  password: pass