create database IF NOT EXISTS configserver;
USE configserver;

CREATE TABLE IF NOT EXISTS PROPERTIES (
  APPLICATION VARCHAR(128) NOT NULL,
  PROFILE     VARCHAR(128) NOT NULL,
  LABEL       VARCHAR(128) NOT NULL,
  `KEY`       VARCHAR(255) NOT NULL,
  `VALUE`       VARCHAR(1048),
  PRIMARY KEY (`KEY`, `APPLICATION`, `PROFILE`, `LABEL`)
);

INSERT INTO PROPERTIES (APPLICATION, PROFILE, LABEL, `KEY`, VALUE)
VALUES ('demo', 'default', 'master', 'app.name', 'Demo');